kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

trigger:
  when:
    branch:
    - master

steps:
- name: Build
  image: rg.fr-par.scw.cloud/serene/llvm:15-8
  commands:
    - cmake --version
    - ./builder build

- name: Linters
  image: rg.fr-par.scw.cloud/serene/llvm:15-8
  commands:
    - pre-commit run cppcheck -a
    - pre-commit run include-what-you-use -a
    - pre-commit run shell-lint -a
