kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

steps:
- name:
  image: rg.fr-par.scw.cloud/serene/llvm:15-7
  commands:
    - ./builder build
  when:
    branch:
    - master
