# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-added-large-files
    - id: check-symlinks
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: forbid-new-submodules
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [--format=json]
