# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-symlinks
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: forbid-new-submodules
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending

  - repo: local
    hooks:
    - id: include-fixer
      name: Fixing 'serene' includes
      language: script
      entry: ./scripts/include-fixer.sh
      files: ".*.(h|cpp)"

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
      - id: cppcheck
        args: ['--project=compile_commands.json']
      - id: include-what-you-use
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    - id: shell-lint
