clone:
   git:
     image: woodpeckerci/plugin-git
     settings:
       depth: 1
       recursive: false

pipeline:
  Prepare:
    image: alpine
    commands:
      - whoami
      - pwd
      - echo $HOME
      - ./builder setup
