site_name: Serene Programming Language
site_description: A modern, typed lisp
site_author: lxsameer
repo_url: https://devheroes.codes/serene/serene
repo_name: Serene
copyright: Copyright &copy; 2019 - 2023 Sameer Rahmani
edit_uri: edit/master/docs/

docs_dir: ./docs/pages
site_dir: ./build/docs

# nav:
#   - Home: 'index.md'
#   - Resources: 'resources.md'

theme:
  name: material
  logo: /images/serene.png
  favicon: /images/serene.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye

  features:
    - content.action.edit
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: amber

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: amber
    # Palette toggle for dark mode




plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search

  # - social:
  #     concurrency: 16
  - tags
      #tags_file: tags.md

  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/mastodon
      link: https://social.lxsameer.com/@lxsameer
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@lxsameer
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/lxsameer

  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - tables
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
