clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Build:
    image: beta.devheroes.codes/serene/ci:9
    commands:
      - pwd
      - ./builder deps pull toolchain
      - ./builder deps pull bdwgc
      - export llvm_version=$(git ls-tree HEAD deps/llvm-project|awk '{print $3}')
      - export bdwgc_version=$(git ls-tree HEAD deps/bdwgc|awk '{print $3}')
      - export PATH=/root/.serene/env/llvm.$${llvm_version}/bin:$PATH
      - export BDWgc_DIR='/root/.serene/env/bdwgc.$${bdwgc_version}/lib64/cmake/bdwgc'
      - ./builder build

    volumes:
      - serene_config:/root/.serene
  Failure:
    image: beta.devheroes.codes/serene/ci:9
    commands:
      - cat /woodpecker/src/beta.devheroes.codes/Serene/serene/build/CMakeFiles/CMakeError.log
    when:
      status: [ failure ]
