clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Build:
    image: devheroes.codes/serene/ci:10
    commands:
      # Uncomment this when running with a new toolchain for the
      # first time to save up space
      # - rm -rf /root/.serene/*
      - ./builder build -DSERENE_DISABLE_CCACHE=ON

    volumes:
      - serene_config:/root/.serene/
