clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Prepare:
    image: beta.devheroes.codes/serene/ci:9
    commands:
      - pwd
      - ./builder deps pull toolchain
      - ./builder deps pull bdwgc
      - export SERENE_AUTO_DEP=true
      - ./builder build

    volumes:
      - serene_config:/root/.serene
