clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Build:
    image: beta.devheroes.codes/serene/ci:9
    commands:
      - ./builder build

    volumes:
      - serene_config:/root/.serene/
