pipeline:
  Prepare:
    image: beta.devheroes.codes/serene/ci:9
    commands:
      - pwd
      - ./builder deps pull toolchain
      - ./builder deps pull bdwgc
      - export SERENE_ROOT=$(pwd)
      - source activate
      - ./builder build

    volumes:
      - serene_config:/root/.serene
