clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Linters:
    image: lxsameer/serene_ci:13
    commands:
      - export SERENE_CI=true
      - ./builder setup
      - export FILES="$(git diff --name-only HEAD HEAD~1)"
      - pre-commit run --files "$FILES"
