clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 1
      lfs: false
      recursive: false

pipeline:
  Linters:
    image: devheroes.codes/serene/ci:10
    commands:
      - ./builder setup
      - export FILES="$(git diff --name-only HEAD HEAD~1)"
      - pre-commit run --files "$FILES"
