pipeline:
  Notify:
    image: lxsameer/notify:3
    settings:
      matrix_room_id:
        from_secret: matrix_room
      matrix_access_token:
        from_secret: matrix_token

      matrix_user:
        from_secret: matrix_user

      matrix_msg: "[${CI_REPO}][<b>FAILED</b>] Branch: ${CI_BRANCH} - Job #${CI_BUILD_NUMBER}"
    when:
      status: [ failure ]

depends_on:
  - lint
  - build

runs_on: [ success, failure ]
skip_clone: true
