pipeline:
  Notify:
    image: lxsameer/notify:3
    settings:
      matrix_room_id:
        from_secret: matrix_room
      matrix_access_token:
        from_secret: matrix_token

      matrix_user:
        from_secret: matrix_user

      matrix_msg: "[${CI_REPO}][<b>FAILED</b>] Branch: ${CI_BRANCH} - Job #${CI_BUILD_NUMBER}"
    when:
      status: [ failure ]

  Mailer:
    image: lxsameer/woodpecker_mailer:4
    settings:
      from: ci@serene-lang.org
      user:
        from_secret: mail_user
      password:
        from_secret: mail_pass
      to: ${CI_COMMIT_AUTHOR_EMAIL}
      subject: "[${CI_REPO}] JOB #${CI_BUILD_NUMBER} - ${CI_PREV_STEP_STATUS}"
      text: |
        BUILD: ${CI_BUILD_LINK}
        COMMIT: ${CI_COMMIT_LINK}
    when:
      status: [ failure ]

depends_on:
  - lint
  - build

runs_on: [ failure ]
skip_clone: true
